[tool.ruff]
# Set the maximum line length to match common Python practices
line-length = 100

# Enable pyflakes `E` and `F` codes by default but exclude some overly strict rules
select = [
    "E4",  # Import errors
    "E7",  # Statement errors  
    "E9",  # Runtime errors
    "F",   # Pyflakes
    "W",   # Warning
]

# Ignore specific rules that are too strict for this project
ignore = [
    "E701",  # Multiple statements on one line (colon)
    "E702",  # Multiple statements on one line (semicolon)
    "F401",  # Imported but unused (we have conditional imports)
    "F841",  # Local variable assigned but never used (common in development)
    "W503",  # Line break before binary operator
    "W504",  # Line break after binary operator
]

# Exclude directories and files that shouldn't be linted
exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "venv",
    "build",
    "dist",
    "external",
    "%USERPROFILE%",
]

# Allow autofix for safe fixes
fix = true

# Assume Python 3.11 since that's what the CI uses
target-version = "py311"

[tool.ruff.per-file-ignores]
# Allow unused imports in __init__.py files
"__init__.py" = ["F401"]
# Be more lenient with test files
"test_*.py" = ["F401", "F841"]
"*test*.py" = ["F401", "F841"]

[tool.mypy]
# MyPy configuration to match the CI
python_version = "3.11"
ignore_missing_imports = true
warn_return_any = false
warn_unused_configs = true
no_implicit_optional = false