name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Stage 1: Lint, Type Check, and Test
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run ruff linter
      run: ruff check .
    
    - name: Run mypy type checker
      run: mypy . --ignore-missing-imports
    
    - name: Run pytest
      run: pytest -q

  # Stage 2: Build Dashboard
  build-dashboard:
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dashboard dependencies
      run: |
        cd dashboard
        npm ci
    
    - name: Build dashboard
      run: |
        cd dashboard
        npm run build
    
    - name: Upload dashboard build artifact
      uses: actions/upload-artifact@v3
      with:
        name: dashboard-dist
        path: dashboard/dist/
        retention-days: 30

  # Stage 3: Smoke Test Agent
  smoke-test:
    runs-on: ubuntu-latest
    needs: [lint-and-test, build-dashboard]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run smoke test agent headless
      run: |
        # Run basic smoke test - check if main modules can be imported
        python -c "import run_agent; print('Agent import successful')"
        
        # Run any existing tests in quiet mode
        if [ -f "test_*.py" ]; then
          python -m pytest test_*.py -q --tb=short
        fi
        
        # Verify agent can be instantiated without errors
        python -c "
        import sys
        try:
            from trading_bot.base_agent import BaseAgent
            print('BaseAgent smoke test passed')
        except ImportError as e:
            print(f'BaseAgent import failed: {e}')
            sys.exit(1)
        except Exception as e:
            print(f'BaseAgent smoke test failed: {e}')
            sys.exit(1)
        "